# Generated by Django 4.2.1 on 2024-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
