# Generated by Django 4.2.1 on 2024-02-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0004_restaurant_sale_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('restaurants', models.ManyToManyField(to='apiuser.restaurant', through='StaffRestaurant')),
            ],
        ),
    ]
