# Generated by Django 4.2.1 on 2024-02-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0005_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='restaurants',
            field=models.ManyToManyField(related_name='staffs', to='apiuser.restaurant',through='StaffRestaurant'  ),
        ),
        migrations.CreateModel(
            name='StaffRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiuser.restaurant')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiuser.staff')),
            ],
        ),
    ]
